### ISSUE TITLE
2023/10/31 指示チューニングのためのデータ形式変換Tips

### ISSUE THREAD

**Issue by oriki101** [elith-co-jp/study-generative-ai#3]
## はじめに

transformers のモデルを用いて指示チューニングを行う際、適切な形式で入力データを整形する必要があります。今回の勉強会では、データ変換を効率的に行うための方法について解説します。

## チャットテンプレート

LLM（大規模言語モデル）をチャットモデルとして利用する際、ユーザーやアシスタントなどの役割ごとにメッセージを分けるためのテンプレートが必要です。これを「チャットテンプレート」と呼びます。チャットテンプレートはモデルによって異なり、適切なテンプレートを使用しないと、パフォーマンスが低下する可能性があります。そのため、各モデルに対応したチャットテンプレートを理解することが重要です。以下に、代表的な LLM のチャットテンプレートを示します。

**LLaMA3**

- テンプレート

```python
<|begin_of_text|><|start_header_id|>system<|end_header_id|>{システムプロンプト}
<|eot_id|><|start_header_id|>user<|end_header_id|>{ユーザーメッセージ}
<|eot_id|><|start_header_id|>assistant<|end_header_id|>
```

- 具体例

```python
<|begin_of_text|><|start_header_id|>system<|end_header_id|>
あなたは優秀な翻訳家です。<|eot_id|><|start_header_id|>user<|end_header_id|>
「こんにちは」を英語にしてください<|eot_id|><|start_header_id|>assistant<|end_header_id|>
```

**gemma2**

- テンプレート
    - gemma2 では LLM でよく利用される system に当たる部分はありません

```python
<bos><start_of_turn>user
{ユーザーメッセージ}<end_of_turn>
<start_of_turn>model
```

- 具体例

```python
<bos><start_of_turn>user
「こんにちは」を英語にしてください。<end_of_turn>
<start_of_turn>model
```

transformersでは、`tokenizer` に定義されたメソッド `apply_chat_template` を利用して、チャットテンプレートを自動的に適用することができます。使い方は非常に簡単で、チャットの各要素を辞書形式のリストとして渡すだけです。

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-70B-Instruct")

messages = [
    {"role": "system", "content": "あなたは優秀な翻訳家です。"},
    {"role": "user", "content": "「こんにちは」を英語にしてください"},
]

prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
```

※昔のモデルでは定義されていないことがあるため、その際はJinja2 テンプレート言語を利用して定義してください。

## DataCollatorForCompletionOnlyLM

指示チューニング（Instruction Tuning）は、LLMが特定の指示に従って応答する能力を向上させる手法です。事前学習と同様に Next Token Prediction で学習します。事前学習との違いとして、指示と応答のペアテキストで学習し、応答に対応する部分でのみ損失を計算します。

PyTorch の `CrossEntropyLoss` ではラベルが-100の場所の損失計算をしない設定となっているため、指示部分のラベルを-100に設定する必要があります。DataCollatorForCompletionOnlyLMを利用することで、この設定を簡略化することができます。

```python
from trl import DataCollatorForCompletionOnlyLM

response_template = "<start_of_turn>model" # gemma のモデル応答部分を指定、モデルにより変更
data_collator = DataCollatorForCompletionOnlyLM(
    response_template=response_template, # response_template以降の部分のみで損失を計算
    tokenizer=tokenizer,
)
```

## おわりに

transformersのモデルを使用して指示チューニングを行う際、入力データの変換を簡便化する方法について紹介しました。これらの方法を活用することで、人手によるエラーが減り、効率的なデータ変換が実現できるため、ぜひ活用してください。

## 参考

- https://huggingface.co/docs/transformers/chat_templating
- [https://huggingface.co/docs/trl/sft_trainer#advanced-usage](https://huggingface.co/docs/trl/sft_trainer)
- https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html

**Comment by aRySt0cat** [comment]
以下のページの `Advanced: Tool use / function calling` によるとツールに関しても `apply_chat_template` に渡せるみたいです。
- https://huggingface.co/docs/transformers/main/chat_templating
